<img src="NTNU_Logo.png" align="left" style="width: 30%">
<br clear="all" />
<br></br>

# Intro til Python

* **Emne IELEA2302 - Signalbehandling**
* **Uke 2, 2021**
    * *Fredag*
* **Underviser: Kai Erik Hoff**


# Tema

* Oppfriskning python syntaks og operatorer
* Lister
* Numpy ndarray
* Innebygde funksjoner i numpy
* Plotting med Matplotlib


# Python syntaks nøkkelpunkt

* Ingen semikolon ved linjeslutt. Interpreteren tolker linjeskift.
    * *Det er lov å dele opp lange funksjonskall etc. over flere linjer.*
* "whitespace" og kolon (`:`) brukes til å definere skop i programmet.

#### Eksempel:

In [1]:
def factorial(x):
    y = 1
    for i in range(x, 0, -1):
        y *= i
    return y


print(factorial(8))

40320


# Operatorer *(og rekkefølge)*

Operasjon | Python-operator | Prioritet | Kommentar
---|---|---|---
Parantes | () | 1 | Alle operasjoner innenfor en parantes utføres _før_ de som står utenfor.
Funksjonskall | f(x, y, z,...) | 2 | Funksjoner som f.eks. `math.sqrt(x)`.
Potensregning | ** | 3 | For å regne ut potensuttrykk av typen $x^y$.
Multiplikasjon | * | 4 | Stjernetegn for vanlig multiplikasjon $x\cdot y$
Divisjon | / | 4 | Skråstrek for vanlig divisjon $\frac{x}{y}$
Heltallsdivisjon | // | 4 | Tilsvarer `int(x/y)`. Runder ned.
Modulo | % | 4 | Rest etter heltallsdivisjon. Tilsvarer `x - int(x/y)*y`.
Addisjon | + | 5 | Plusstegn for vanlig addisjon $x+y$.
Subtraksjon | - | 5 | Minustegn for vanlig subtraksjon $x - y$.

# Tilordning og Sammensatte Operatorer

Operasjon | Python-operator | Eksempel på bruk | Kommentar
---|---|---|---
Tilordning | `=` | `x=a` | Tilordning av verdi `a` til variabel `x`.
Inkrement | `+=` | `x+=a` | Tilsvarer `x = x + a`.
Dekrement | `-=` | `x-=a` | Tilsvarer `x = x - a`.
Multiplikasjon med tilordning | `*=` | `x*=a` | Tilsvarer `x = x*a`.
Divisjon med tilordning | `/=` | `x/=a` | Tilsvarer `x = x/a`.
Heltallsdivisjon med tilordning | `//=` | `x//=a` | Tilsvarer `x = x//a`.
Modulo med tilordning | `%=` | `x%=a` | Tilsvarer `x = x%a`.
Eksponent med tilordning | `**=` | `x**=a` | Tilsvarer `x = x**a`.


# Sekvenser

* **Sekvens:** et objekt som inneholder flere dataenheter
    * Enhetene lagres i sekvens (etter hverandre)
* Python har en rekke ulike sekvenstyper
    * Noen "Standardtyper":
        * Liste `list`
        * Tekststreng `str`
    * Sentralt for Signalbehandling:
        * Nympy sin array `numpy.ndarray` 
    * Annet:
        * Iterable (range)
        * Tuple
        * osv..

* Digitale signal er, når alt kommer til alt, bare en sekvens med tall.
    * Sekvenstyper er dermed en naturlig måte for python (eller andre programmeringsspråk) å håndtere et digitalt signal på.

## Lister
* Python sin "default" sekvenstype.
* Opprettelse av liste i Python gjøres på formen:
```python
variabelnavn = [element1, element2, element3, …]
```
* Her er et eksempel på en liste i Python:
```python
liste = [’Ole’, ’Dole’, ’Doffen’]
```
* Veldig fleksibel.
    * Det er mulig å blande datatyper for enhetene i listen.
    * Man kan gjøre endringer på listens lengde underveis.

## Eksempel:

In [2]:
liste = [9, 'epler', 'veier', 3.4, 'kg']
print(liste)
print(len(liste))
liste.append('appelsiner')
print(liste)
print(len(liste))

[9, 'epler', 'veier', 3.4, 'kg']
5
[9, 'epler', 'veier', 3.4, 'kg', 'appelsiner']
6


# Generering av lister med tallverdier
* Vi bruker funksjonene `list()` og `range()` når vi ønsker en liste unifromt med stigende/synkende tallverdier.
* For å opprette en liste som følger en matematisk formel, kan vi bruke en litt spesiell anvendelse av for-løkken.
```python
[f_av_i for i in [verdi1, verdi2, osv..]]
```

## Eksempel:

In [3]:
x = list(range(0, 50, 1))

y = [i**0.5 for i in x]


# Repetisjon og sammenslåing

* Operatorene `*` og `+` brukes til repetisjon og sammenslåing av lister.

In [4]:
x = [1, 2, 3, 4]
y = x*6 # Repetisjon av listen x
print(y)

y = [5]
z = x + y # Slå sammen listene x og y
print(z)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 5]


# Indeksering

* **Indeks:** et tall som spesifiserer et elements posisjon i en liste
    * Gir tilgang til de enkelte elementer i listen
    * Indeksen til det første elementet er 0, det andre 1, og det n-te elementet er $n-1$.
    * Negative indekser identifiserer posisjone relativt til listens slutt.
    ![](Figurer/02_Pythonkurs/01_Indeksillustrasjon.png)

# Bruk av indeksering

* For å få tak i innholdet for et bestemt element i en liste, skriver man variabelnavnet, firkantparantes og indeks-nummeret til elementetm f.eks: `x = liste[3]`
* På samme måte kan enkelt-elementer overskrives med å indeksere et bestemt element, f.eks: `liste[3] = 99`

In [5]:
from random import randint
liste = [randint(0, 9) for i in range(10)]
print("Liste: ", liste)
print("verdien i posisjon 3 er: ", liste[3])
liste[3] = 12
print("Listen er nå: ", liste)

Liste:  [6, 3, 3, 7, 8, 1, 1, 6, 1, 8]
verdien i posisjon 3 er:  7
Listen er nå:  [6, 3, 3, 12, 8, 1, 1, 6, 1, 8]


# Liste-"slicing"

* **Slice:** en "sub-liste" av enheter som er tatt fra en sekvens. 
    * Slicing format: `liste[start:stopp:steg]`
    * Resultatet er en liste som inneholder kopier av elementer med indekser fra`start` fram til (men ikke inkludert) `stopp`, hvor intervallet mellom hver av indeksene er `steg`.
        * Indeksene tilsvarer elementene i `range(start, stopp, steg)`
        * Hvis `start` ikke er spesifisert, brukes `0` som startindeks
        * Hvis `stopp` ikke er spesifisert, brukes `len(list)` som sluttindeks
        * Hvis `steg` ikke er spesifisert, brukes `1` som stegintervall.
    * Slicing-uttrykk kan inneholde stegverdier og negative indekser, som er relative til listens slutt   

In [6]:
xList = list(range(0, 21))
yList = xList[10::2]
print(yList)

[10, 12, 14, 16, 18, 20]


## Kodeeksempel: 

* Fullfør funksjonen `reverser(liste)` som returnerer listen `liste` der elementene nå er i motsatt rekkefølge. 
    * Funksjonen skal oppnå dette med bruk av *slicing*

In [7]:
def reverser(liste):
    #--------------------
    nyListe = liste[::-1]
    #--------------------
    return nyListe

xListe = list(range(22))
yListe = reverser(xListe)
print(yListe)

[21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


# Metoder

* Spesielle funksjoner som er "bakt inn" i definisjonen av en datatype/klasse.
* Lister har en rekke innebgyde metoder du kan lese om [her](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists). 
* Noen ofte brukte metoder er:
    * `append(x)`: Legger til et element `x` på slutten av lista.
    * `insert(indeks, x)`: Setter inn element `x` i indeks `indeks`. Alle elementer etter `indeks` blir forskjøvet.
    * `pop(indeks)`: Fjern element i posisjon `indeks` fra lista, og returner verdien.
    * `index(x)`: Returner posisjonen til den første instansen av verdien `x` i lista.

# Hvorfor bruke numpy?

* Å bruke lister til å håndtere digitale signal vil ha noen begrensninger:
    * Vi har i grunn ikke behov for å "blande" datatyper i liste-elementene.
    * Tungvindt å gjøre elementvise regneoperasjoner.
    * Prosesseringstiden er høy. Dette vil merkes på store signal (f.eks. en musikkfil).

* Numpy er et bibliotek med funksjoner og variabeltyper som fasiliterer numeriske utregninger med tidvis store datasett.
* Variabeltypen `numpy.ndarray` er sentral for hele modulen. Dette er en listelignende variabeltype med innebygd støtte for enkle utregninger av matematiske formler, matriseoperasjoner etc.

# Om `ndarray`

* Sekvenstype spesielt tilpasset numeriske utregnigner.
* Tillater bruk av de vanlige aritmetiske operatorene til å gjøre beregninger på *hvert element* i listen.
* Størrelsen på en `ndarray` er statisk, og kan ikke endres. Skal du legge til en ny verdi på slutten av arrayen må du lage en helt ny array. 
* Det er heller ikke mulig å "blande" datatyper.

# Å opprette en array
* Begynn med å importere modulen:
```python
import numpy as np
```
* Alternativ 1 er å konvertere fra liste til array med funksjonen `np.array()`
```python
x = np.array([2, 1, 4, 0])
```
* Alternativ 2 er å bruke numpy-funksjoner som lager arrays:
```python
np.arange(start, stop, step)
np.linspace(start, stop, n_of_steps)
np.zeros(N)
```

## `arange(start, stop, step)`:
* Fungerer veldig likt standard-funksjonen range, men returnerer en array.
* Returnert array er tall i rekkefølge f.o.m. `start`, med intervall `step` mellom hver verdi helt til man når max-verdien `stop`. Siste verdi i array vil være mindre enn `stop`
* Eksempel på kjøring:
```python
np.arange(10,2,-2)
```
    Gir `array([10, 8, 6, 4])`
    


## `linspace(start, stop, n_of_steps)`:
* Returnerer en array med lengde `n_of_steps`, der verdiene følger intervallet fra `start` til `stop`.
* Siste verdi i array vil være `stop` i motsetning til `arange()`
* Intervallet mellom hver verdi vil være: `(stop-start)/(n_of_steps-1)`
* Man kan ekskludere verdien `stop` ved å sette parameteren `endpoint=false`
* Eksempel på kjøring:
```python
np.linspace(10, 2, 4, endpoint=False)
```
    Gir `[10., 8., 6., 4.]`
    
* Numpy-dokumentasjonen anbefaler å bruke `linspace()` hvis man skal generere en array med flyttall.

## Kodeeksempel:

In [8]:
import numpy as np

# Ulike måter å generere en eksponentiell array
listA = np.array([1, 2, 4, 8, 16])
print(listA)

listB = 2**np.arange(0, 5)
print(listB)

listC = 2**np.linspace(0, 4, 5)
print(listC)

listD = np.logspace(0, 4, 5, base=2)
print(listD)

[ 1  2  4  8 16]
[ 1  2  4  8 16]
[ 1.  2.  4.  8. 16.]
[ 1.  2.  4.  8. 16.]


# Behandling av hvert element i en array

* Dersom en skal regne ut en rekke verdier for en funksjon $f(x)$, gjøres det typisk i 2 steg.
    1. Generer alle de interessante verdiene av variabelen $x$.
    2. Disse videre som utgangspunkt til å regne ut funksjonferdiene $f(x)$.

* Med lister må dette utføres med en for-løkke:
```python
f_x = [x**2 for x in range(10)]
```
* Med Numpy blir prosessen både enklere og mer intuitiv, så snart vi får laget et array med x-verdier:
```python
x = np.arange(10)
f_x = x**2
```

## Kodeeksempel: 
* Regn ut de ti første tallene i rekken $x_n = 2^n$

In [9]:
n = np.arange(0, 10)
x_n = 2**n

print(x_n)

[  1   2   4   8  16  32  64 128 256 512]


# Regneoperasjoner med arrays:

```python
A = np.array([[1, 0],
              [1, 2]])
```

|**Med Numpy** | **I matematikken** |**Med Numpy** | **I matematikken**|
|---|---|---|---|
|`A + 5` | $$ \begin{bmatrix} 1+5 & 0+5 \\ 1+5 & 2+5 \end{bmatrix} = \begin{bmatrix} 6 & 5 \\ 6 & 7 \end{bmatrix} $$| `A - 5` | $$ \begin{bmatrix} 1-5 & 0-5 \\ 1-5 & 2-5 \end{bmatrix} = \begin{bmatrix} -4 & -5 \\ -4 & -3 \end{bmatrix} $$
|`A * 5` | $$ \begin{bmatrix} 1\cdot5 & 0\cdot5 \\ 1\cdot5 & 2\cdot5 \end{bmatrix} = \begin{bmatrix} 10& 0 \\ 10 & 20 \end{bmatrix} $$|`A @ A` | $$ \begin{bmatrix} 1 & 0 \\ 1 & 2 \end{bmatrix} \cdot \begin{bmatrix} 1 & 0 \\ 1 & 2 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 3 & 4 \end{bmatrix} $$|
|`A / 5` | $$ \begin{bmatrix} \frac{1}{5} & \frac{0}{5} \\ \frac{1}{5} & \frac{2}{5} \end{bmatrix} = \begin{bmatrix} 0.2 & 0.0 \\ 0.2 & 0.4 \end{bmatrix} $$|`5 / A` | $$ \begin{bmatrix} \frac{5}{1} & \frac{5}{0} \\ \frac{5}{1} & \frac{5}{2} \end{bmatrix} = \begin{bmatrix} 5.0 & \infty \\ 5.0 & 2.5 \end{bmatrix} $$|
|`A ** 2` | $$ \begin{bmatrix} 1^2 & 0^2 \\ 1^2 & 2^2 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 1 & 4 \end{bmatrix} $$|`2 ** A` | $$ \begin{bmatrix} 2^1 & 2^0 \\ 2^1 & 2^2 \end{bmatrix} = \begin{bmatrix} 2 & 1 \\ 2 & 4 \end{bmatrix} $$|
|`A ** A` | $$ \begin{bmatrix} 1^1 & 0^0 \\ 1^1 & 2^2 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 1 & 4 \end{bmatrix} $$|`A + A` | $$ \begin{bmatrix} 1+1 & 0+0 \\ 1+1 & 2+2 \end{bmatrix} = \begin{bmatrix} 2 & 0 \\ 2 & 4 \end{bmatrix} $$|


## Kodeeksempel:
* Generer arrayer x og y som representerer x/y koordinatene til 51 punkt langs kurven til funksjonen $y=\frac{x^3}{3} + 2\cdot x^2 -8\cdot x -12$ i intervallet $-3 \leq x \leq 3$

In [10]:
x = np.linspace(-3, 3, 51)

y = x**3/3+2*x**2-8*x-12
print(y)

[ 21.        19.666176  18.307008  16.925952  15.526464  14.112
  12.686016  11.251968   9.813312   8.373504   6.936      5.504256
   4.081728   2.671872   1.278144  -0.096     -1.447104  -2.771712
  -4.066368  -5.327616  -6.552     -7.736064  -8.876352  -9.969408
 -11.011776 -12.       -12.930624 -13.800192 -14.605248 -15.342336
 -16.008    -16.598784 -17.111232 -17.541888 -17.887296 -18.144
 -18.308544 -18.377472 -18.347328 -18.214656 -17.976    -17.627904
 -17.166912 -16.589568 -15.892416 -15.072    -14.124864 -13.047552
 -11.836608 -10.488576  -9.      ]


# Noen matematiske funksjoner:

* Numpy har også egne array-kompatible funksjoner for alle de vanlige matematiske operasjonene.
    * Det skal ikke være nødvendig å importere `math` i tillegg til `numpy`.

```python
A = np.array([[1, 0],
              [1, 2]])
```

|**Med Numpy** | **I Matematikken**|
|---|---|
|`np.cos(A)`| $$ \begin{bmatrix} \cos(1) & \cos(0) \\ \cos(1) & \cos(2) \end{bmatrix}$$
|`np.sin(A)`| $$ \begin{bmatrix} \sin(1) & \sin(0) \\ \sin(1) & \sin(2) \end{bmatrix}$$
|`np.exp(A)`| $$ \begin{bmatrix} e^1 & e^0 \\ e^1 & e^2 \end{bmatrix}$$
|`np.log10(A)`| $$ \begin{bmatrix} \log_{10}(1) & \log_{10}(0) \\ \log_{10}(1) & \log_{10}(2) \end{bmatrix}$$

## Kodeeksempel
* Signalet $x(t)$ er gitt ved funksjonsuttrykket $x(t) = e^{-0.2t}\cdot \cos\left(20\pi \cdot t \right)$. Generer en array `xt` med signalverdiene $x(t)$ for 500 verdier av $t$  i intervallet $0 \leq t < 2$.

In [11]:
import matplotlib.pyplot as plt
from numpy import exp, cos, pi
%matplotlib ipympl

t = np.linspace(0, 2, 500, endpoint=False)
x_t = exp(-0.2*t)*cos(20*pi*t)

plt.figure(1)
plt.plot(t, x_t)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

* Den mest fornuftige måten å representere slike lange arrays på er å lage en grafisk fremstilling.
* Det er her `matplotlib` kommer inn i bildet.

# Hva er matplotlib?

* Bibliotek for visualisering av data, matematiske funksjonsuttrykk og mye mer.
* Svært nyttig for å visualisere tidvis vanskelige konsepter.
* Vi får tilgang til modulen ved å importere `matplotlib.pyplot`

In [12]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib ipympl

x = np.outer(np.linspace(-2, 2, 101), np.ones(101))
y = x.copy().T # transpose
z = x + 1j*y
Hz = (z+1)/(z-0.9)

fig = plt.figure(figsize=(8,8))
ax = plt.axes(projection='3d')

ax.plot_surface(x, y, 20*np.log10(abs(Hz)),cmap='viridis', edgecolor='none');
ax.set_title('Surface plot')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

<ipython-input-12-5bd38efa3dc3>:13: RuntimeWarning: divide by zero encountered in log10
  ax.plot_surface(x, y, 20*np.log10(abs(Hz)),cmap='viridis', edgecolor='none');


# Oppsett i Jupyter Notebook

* Matplotlib har nærmest ubegrensede muligheter for å konfigurere bakgrunn, figurstil osv..
    * Her er det lett å rote seg litt bort, og vi kommer i hovedsak til å holde oss til "the basics".
* Vi bruker "default"-stilen for plot, men integrert i Jypyter Notebook. Dette kan gjøres ved å kjøre følgende linje:
```python
%matplotlib ipympl
```
* Figurene vil nå være interaktive, slik at man kan endre størrelse, zoome inn og ut på figuren osv.

# Funksjonen `plot()`

* Brukes til å plotte en graf basert på x- og y- koordinater.
* Skrivemåte: `plot(x, y)` (`x` og `y` er sekvenser med tall)
    * Krav: x og y må ha like mange element
    * Koordinatene til det første punktet på grafen er `x[0], y[0]`, så `x[1], y[1]` osv... 
    * `x` og `y` angir altså en serie med punkt på et kartesisk koordinatsystem. Grafen lages ved å tegne strek fra punkt til punkt.
* *P.S. Dersom man skal opprette en ny figur må man kalle funksjonen `figure()` før man begynner å plotte* 

# "Pynting" på figuren
* `title()` Gi figuren en tittel
* `xlabel()` Gi x-aksen et navn
* `ylabel()` Gi y-aksen et navn
* `grid(True/False)` Aktiver/deaktiver rutenett
* `xlim() / ylim()` Avgrensing av x- og y-akse

In [13]:
plt.close(2)
plt.figure(2, figsize=(8,6))
plt.plot(t, x_t)
plt.xlabel("Tid t (s)")
plt.ylabel("x(t)")
plt.title("Dempet sinusbølge")
plt.grid(True)
plt.xlim([0, 2]);

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# Andre funksjoner for figurer
* `figure()` Åpne en ny figur
    * Du kan angi størrelsen på figuren med parameteren `figsize`: `plt.figure(1, figsize=(20,20))`
* `bar()` Lag et søylediagram
* `scatter()` Plot kun punktene
* `stem()` Stolpediagram
* `loglog()` Tegn en graf med logaritmiske x- og y-akser
* `semilogx()` Tegn en graf med logaritmisk x-akse
* `semilogy()` Tegn en graf med logaritmisk y-akse

## Eksempel: Logaritmiske akser

In [21]:
plt.close(3)
plt.figure(3, figsize=(8,6))


x = np.logspace(0, 5, 1001)
y = 1/x

plt.semilogx(x, y)
plt.xlim(0, 100000)
plt.grid(True)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

<ipython-input-21-5e05e3194b33>:9: UserWarning: Attempted to set non-positive left xlim on a log-scaled axis.
Invalid limit will be ignored.
  plt.xlim(0, 100000)


## Eksempel: Tegn en likesidet trekant

In [24]:
plt.close(4)
plt.figure(4, figsize=(6,6))

from numpy import sin

theta = np.array([pi/2, 7*pi/6, 11*pi/6, pi/2])

x = cos(theta)
y = sin(theta)

plt.plot(x, y)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# Subplot
* Brukes når du vil lage to adskilte grafer i samme figur.
* Funksjonen `subplot(rows, cols, pos)` vil dele opp figuren i et rutenett, og "aktiverer" de(n) ruten(e) angitt i `pos`.
* Ved å f.eks. skrive `plt.subplot(2,3,5)`, vil "hovedfiguren" deles opp på følgende vis:
| |  |  |
| --- | --- | --- |
| 1 | 2 | 3 |
| 4 | [5] | 6 |

In [27]:
plt.close(5)
plt.figure(5, figsize=(10,6))

theta1 = np.array([pi/2, 7*pi/6, 11*pi/6, pi/2])

x1 = cos(theta)
y1 = sin(theta)
plt.subplot(1,2,1)
plt.plot(x1, y1)

theta2 = np.linspace(0, 2*pi, 501)
x2 = cos(theta2)
y2 = sin(theta2)
plt.subplot(1,2,2)
plt.plot(x2,y2)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# Labels
* Når man har mange grafer i samme figur, kan det være nyttig å gi de merkelapper.
* Funksjonen `plot()` har et valgfritt agument `label` som kan benyttes til å gi kurven et navn.
* Funksjonen `legend()` kan deretter brukes for å vise merkelappen, justere posisjon etc.

In [32]:
plt.close(6)
plt.figure(6, figsize=(6,6))

theta1 = np.array([pi/2, 7*pi/6, 11*pi/6, pi/2])

x1 = cos(theta)
y1 = sin(theta)
plt.plot(x1, y1, label='trekant')

theta2 = np.linspace(0, 2*pi, 501)
x2 = cos(theta2)
y2 = sin(theta2)
plt.plot(x2,y2, label='sirkel')

plt.legend(loc='upper right')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# Spørsmål?